apiVersion: v1
kind: Namespace
metadata:
  name: crd-test
  labels:
    name: crd-test
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmonitors.magalix.com
  namespace: crd-test
spec:
  scope: Namespaced
  group: magalix.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              configMap:
                type: string
                description: "Name of the ConfigMap to watch for changes"
              podSelector:
                type: object
                description: "Label selector used for selecting Pods"
                additionalProperties:
                  type: string
  names:
    kind: ConfigMonitor
    singular: configmonitor
    plural: configmonitors
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: crd-operator-sa
    namespace: crd-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crd-role
  namespace: crd-test
rules:
- apiGroups:
  - magalix.com
  resources:
  - configmonitors
  - configmonitors/finalizers
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: core-api-rolebinding
  namespace: crd-test
  labels:
    app: crd-rbac
subjects:
- kind: ServiceAccount #Group
  name: crd-operator-sa #system:serviceaccounts
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-rolebinding
  namespace: crd-test
  labels:
    app: crd-rbac
subjects:
- kind: ServiceAccount
  name: crd-operator-sa
  namespace: crd-test
roleRef:
  kind: Role
  name: crd-role
  apiGroup: rbac.authorization.k8s.io
